const temp = [
    {key: "Header_MainMenu_Dashboard", en: "Dashboard", cn: "仪表板"},
    {key: "Header_MainMenu_Explore", en: "Explore", cn: "探索"},
    {
        key: "Header_MainMenu_Explore_AllEquipment",
        en: "All equipment",
        cn: "所有装备",
    },
    {
        key: "Header_MainMenu_Explore_2D3DView",
        en: "2D/3D view",
        cn: "2D / 3D视图",
    },
    {
        key: "Header_MainMenu_Explore_Connectivity",
        en: "Connectivity",
        cn: "连接性",
    },
    {
        key: "Header_MainMenu_Explore_HierarchicalView",
        en: "Hierarchical view",
        cn: "分层视图",
    },
    {
        key: "Header_MainMenu_Settings_UsersAndGroups_Groups",
        en: "Groups",
        cn: "组",
    },
    {
        key: "Header_MainMenu_DataAnalytics",
        en: "Data analytics",
        cn: "数据分析",
    },
    {
        key: "Header_MainMenu_DataAnalytics_DataGroups",
        en: "Data groups",
        cn: "数据组",
    },
    {
        key: "Header_MainMenu_DataAnalytics_Reports",
        en: "Reports",
        cn: "报告",
    },
    {key: "Header_MainMenu_Automation", en: "Automation", cn: "自动化"},
    {
        key: "Header_MainMenu_DataAnalytics_Reports_GenerateReport",
        en: "Generate report",
        cn: "生成报告",
    },
    {
        key: "Header_MainMenu_DataAnalytics_Reports_ScheduledTask",
        en: "Scheduled task",
        cn: "计划任务",
    },
    {
        key: "Header_MainMenu_DataAnalytics_Reports_History",
        en: "History",
        cn: "历史",
    },
    {
        key: "Header_MainMenu_DataAnalytics_RuleManagement",
        en: "Rule management",
        cn: "规则管理",
    },
    {key: "Header_MainMenu_Maintenance", en: "Maintenance", cn: "维护"},
    {key: "Header_MainMenu_Events", en: "Events", cn: "事件"},
    {key: "Header_MainMenu_Events_All", en: "All events", cn: "所有事件"},
    {
        key: "Header_MainMenu_Events_AlertCondition",
        en: "Alert condition",
        cn: "警报条件",
    },
    {key: "Header_MainMenu_Settings", en: "Settings", cn: "设置"},
    {key: "Header_MainMenu_Settings_Site", en: "Site", cn: "站点"},
    {
        key: "Header_MainMenu_Settings_Documentation",
        en: "Documentation",
        cn: "文档",
    },
    {
        key: "Header_MainMenu_Settings_UsersAndGroups",
        en: "Users",
        cn: "用户",
    },
    {
        key: "Header_MainMenu_Settings_UsersAndGroups_Users",
        en: "Users",
        cn: "用户",
    },
    {
        key: "Header_MainMenu_Settings_UsersAndGroups_ActivitiesLog",
        en: "Activities log",
        cn: "活动日志",
    },
    {
        key: "Header_MainMenu_Settings_Utility",
        en: "Utility",
        cn: "设施总功率",
    },
    {
        key: "Header_MainMenu_Settings_ServiceAndEnvironment",
        en: "Service and environment",
        cn: "服务与环境",
    },
    {
        key: "Header_MainMenu_Settings_SMSAndNotification",
        en: "Notification",
        cn: "通知",
    },
    {
        key: "Header_MainMenu_Settings_Advanced",
        en: "Advanced",
        cn: "高级",
    },
    {
        key: "Header_MainMenu_Settings_Subscriptions",
        en: "Subscriptions",
        cn: "订阅",
    },
    {
        key: "Header_MainMenu_Settings_ProfileSettings",
        en: "Profile settings",
        cn: "配置文件设置",
    },
    {key: "Header_MainMenu_Settings_Logout", en: "Logout", cn: "注销"},
    {
        key: "Header_MainMenu_Settings_Language",
        en: "Language",
        cn: "语言",
    },
    {
        key: "Header_MainMenu_Settings_NotificationSettings",
        en: "Notification settings",
        cn: "通知设置",
    },
    {
        key: "Header_MainMenu_Settings_Feedback",
        en: "Feedback",
        cn: "反馈",
    },
    {key: "Header_MainMenu_Settings_Support", en: "Support", cn: "支持"},
    {
        key: "Header_MainMenu_Settings_About",
        en: "About ABB Ability",
        cn: "关于 ABB Ability",
    },
    {
        key: "Header_MainMenu_Settings_ForMoreInformation",
        en: "For more information",
        cn: "想要查询更多的信息",
    },
    {
        key: "Footer_Copyright",
        en: "Copyright 2019-2020 ABB. All rights reserved",
        cn: "版权所有2019-2020 ABB。版权所有",
    },
    {
        key: "Footer_Menu_VisitOurWebSite",
        en: "Visit our Web Site",
        cn: "访问我们的网站",
    },
    {
        key: "Footer_Menu_ABBPrivacyPolicy",
        en: "ABB Privacy Policy",
        cn: "ABB隐私政策",
    },
    {
        key: "Footer_Menu_ABBAbilityTermsAndConditions",
        en: "ABB Ability™ Terms and Conditions",
        cn: "ABB Ability™条款和条件",
    },
    {
        key: "Footer_Menu_TermsOfServices",
        en: "Terms of Use",
        cn: "使用条款",
    },
    {
        key: "Footer_Menu_AcceptableUsePolicy",
        en: "Acceptable use policy",
        cn: "使用政策",
    },
    {
        key: "Footer_Menu_CyberSecurity",
        en: "Cyber security",
        cn: "网络安全",
    },
    {
        key: "Footer_Menu_OpenSourceSoftware",
        en: "Open Source Software",
        cn: "开源软件",
    },
    {key: "Footer_Menu_ContactUs", en: "Contact us", cn: "联系我们"},
    {
        key: "Empty_Dashboard",
        en: "The dashboard is empty",
        cn: "仪表板是空的",
    },
    {
        key: "Empty_Dashboard_sub_title",
        en: "Add widgets from the list and arrange them as you like",
        cn: "从列表中添加小部件并根据需要进行排列",
    },
    {key: "widgetDelete", en: "Delete", cn: "删除"},
    {key: "widgetPage", en: "Page", cn: "页"},
    {
        key: "Dashboard_Widget_AssetList_Table_Column_Name",
        en: "NAME",
        cn: "名称",
    },
    {
        key: "Dashboard_Widget_AssetList_Table_Column_Condition",
        en: "CONDITION",
        cn: "状况",
    },
    {
        key: "Dashboard_Widget_AssetList_Table_Column_Connection",
        en: "CONNECTION",
        cn: "连接",
    },
    {
        key: "Dashboard_Widget_AssetList_Table_Column_HealthIndex",
        en: "HEALTH INDEX (%)",
        cn: "健康系数（％）",
    },
    {
        key: "Dashboard_Widget_AssetList_Selector_HealthIndex_Label",
        en: "Health Index",
        cn: "健康系数",
    },
    {
        key: "Dashboard_Widget_AssetList_equipments",
        en: "Equipments",
        cn: "设备",
    },
    {
        key: "Dashboard_Widget_AssetList_Connected",
        en: "Connected",
        cn: "已连接",
    },
    {
        key: "Dashboard_Widget_AssetList_Disconnected",
        en: "Disconnected",
        cn: "已断开",
    },
    {
        key: "Dashboard_Widget_AssetList_Disabled",
        en: "Disabled",
        cn: "禁用",
    },
    {
        key: "Add_Dashboard_Header",
        en: "ADD A NEW DASHBOARD",
        cn: "新增仪表盘",
    },
    {key: "Add_Dashboard_Settings", en: "SETTINGS", cn: "设置"},
    {key: "Add_Dashboard_Template", en: "Template", cn: "模板"},
    {key: "Add_Dashboard_Name", en: "Name", cn: "名称"},
    {
        key: "Add_Dashboard_Same_Name",
        en: "Name is already in use, Please provide other name",
        cn: "名称已被使用，请提供其他名称",
    },
    {
        key: "Add_Dashboard_Custom_Template",
        en: "Add your custom template to this plant. This template will be available only on this plant and has the same name of this dashboard.",
        cn: "将自定义模板添加到该工厂。 该模板仅在该工厂上可用，并且具有与该仪表板相同的名称。",
    },
    {
        key: "Add_Dashboard_Custom_Template_Added",
        en: "Custom template added",
        cn: "已添加自定义模板",
    },
    {key: "Cancel", en: "Cancel", cn: "取消"},
    {key: "Save", en: "Save", cn: "保存"},
    {
        key: "Total_facility_power",
        en: "Total facility power",
        cn: "设施总功率",
    },
    {
        key: "IT_equipment_power",
        en: "IT equipment power",
        cn: "IT设备电源",
    },
    {key: "kW", en: "kW", cn: "kW"},
    {
        key: "The_Start_Value_Should_Be_Less_Than_End",
        en: "The start value should be less than end",
        cn: "起始值应小于结束值",
    },
    {
        key: "You_Dont_Have_Permission_To_Access_This_Page",
        en: "You don't have permission to access this page",
        cn: "您无权访问此页面",
    },
    {
        key: "Data_is_not_available_for_this_plant",
        en: "Data is not available for this plant",
        cn: "该工厂没有数据",
    },
    {key: "Active_power", en: "Active power", cn: "有功功率"},
    {
        key: "Next_maintenance_date",
        en: "Next maintenance date",
        cn: "下次维护日期",
    },
    {
        key: "Site_generator_capacity",
        en: "Site generator capacity",
        cn: "发电容量",
    },
    {key: "Generated_power", en: "Generated power", cn: "发电量"},
    {key: "Search", en: "Search", cn: "搜索"},
    {key: "Search...", en: "Search...", cn: "搜索..."},
    {key: "Highlights", en: "Highlights", cn: "强调"},
    {
        key: "confidence_Interval",
        en: "Confidence interval",
        cn: "置信区间",
    },
    {key: "previousPower", en: "Previous Power", cn: "先前功率"},
    {key: "previousCost", en: "Previous Cost", cn: "先前成本"},
    {
        key: "Add_a_new_alert_on_the_Alerts_page",
        en: "Add a new alert on the Alerts page",
        cn: "添加新建警报",
    },
    {
        key: "No_reports_available",
        en: "No reports available",
        cn: "无可用报告",
    },
    {key: "Select_period", en: "Select period...", cn: "选择时间段..."},
    {key: "Select_asset", en: "Select asset...", cn: "选择资产..."},
    {
        key: "Go_to_Asset_section",
        en: "Go to Asset section",
        cn: "转到资产部分",
    },
    {key: "No_Results_Found", en: "No results found", cn: "未找到结果"},
    {key: "pueTrendGroup_legend", en: "Group", cn: "组"},
    {
        key: "pueTrendCompareGroup_legend",
        en: "Compare group",
        cn: "比较组",
    },
    {key: "Service_contact", en: "Service contact", cn: "服务联络人"},
    {key: "Send", en: "Send", cn: "发送"},
    {
        key: "The_event_list_is_empty",
        en: "The event list is empty",
        cn: "事件列表为空",
    },
    {key: "Select_group", en: "Select group...", cn: "选择组..."},
    {
        key: "Select_voltage_type",
        en: "Select voltage type...",
        cn: "选择电压类型...",
    },
    {
        key: "Select_manufacturer",
        en: "Select manufacturer...",
        cn: "选择制造商...",
    },
    {
        key: "Select_asset_class",
        en: "Select asset class...",
        cn: "选择资产类别...",
    },
    {key: "Select_Measure", en: "Select measure", cn: "选择测量"},
    {key: "Select_Period", en: "Select period'", cn: "选择时间段..."},
    {
        key: "Select_asset_version",
        en: "Select asset version",
        cn: "选择资产版本",
    },
    {
        key: "Select_asset_family",
        en: "Select asset family",
        cn: "选择资产分类",
    },
    {
        key: "Select_standard_reference",
        en: "Select standard reference",
        cn: "选择标准参考",
    },
    {
        key: "Select_asset_type",
        en: "Select asset type",
        cn: "选择资产类型",
    },
    {
        key: "Select_asset_pole",
        en: "Select asset pole",
        cn: "选择资产极点",
    },
    {
        key: "Dashboard_Widget_EnergyMixGroup_Title",
        en: "Energy Mix Group",
        cn: "能源组合分组",
    },
    {
        key: "Dashboard_Widget_AnalogDataMonitoring_Title",
        en: "Analog Data Monitoring",
        cn: "模拟数据监控",
    },
    {
        key: "Dashboard_Widget_AssetCurrentTrend_Title",
        en: "Asset Current Trend",
        cn: "资产当前趋势",
    },
    {
        key: "Dashboard_Widget_AssetList_Title",
        en: "Asset List",
        cn: "资产清单",
    },
    {
        key: "Dashboard_Widget_AssetPowerData_Title",
        en: "Asset Power Trend",
        cn: "资产功率趋势",
    },
    {
        key: "Dashboard_Widget_AssetVoltageTrend_Title",
        en: "Asset Voltage Trend",
        cn: "资产电压趋势",
    },
    {
        key: "Dashboard_Widget_ConnectivityOverview_Title",
        en: "Connectivity Overview",
        cn: "连接性概述",
    },
    {
        key: "Dashboard_Widget_ConnectivityTrend_Title",
        en: "Connectivity Trend",
        cn: "连接趋势",
    },
    {
        key: "Dashboard_Widget_DigitalDataMonitoring_Title",
        en: "Digital Data Monitoring",
        cn: "数字数据监控",
    },
    {
        key: "Dashboard_Widget_EnergyCost_Title",
        en: "Energy Cost",
        cn: "能源成本",
    },
    {
        key: "Dashboard_Widget_EnergyMonitoring_Title",
        en: "Energy Monitoring",
        cn: "能源监控",
    },
    {
        key: "Dashboard_Widget_EventsOverview_Title",
        en: "Events Overview",
        cn: "事件总览",
    },
    {
        key: "Dashboard_Widget_EventsTrend_Title",
        en: "Events Trend",
        cn: "事件趋势",
    },
    {
        key: "Dashboard_Widget_GroupPeakMonitoring_Title",
        en: "Group Peak Monitoring",
        cn: "组峰值监控",
    },
    {
        key: "Dashboard_Widget_MultiPeakMonitoring_Title",
        en: "Multi Asset Power Peak Monitoring",
        cn: "多资产功率峰值监控",
    },
    {
        key: "Dashboard_Widget_HealthByAge_Title",
        en: "Health by Age",
        cn: "年龄健康",
    },
    {
        key: "Dashboard_Widget_HealthOverview_Title",
        en: "Health Overview",
        cn: "健康概况",
    },
    {
        key: "Dashboard_Widget_LatestEvents_Title",
        en: "Latest Events",
        cn: "最新活动",
    },
    {
        key: "Dashboard_Widget_LocalTime_Title",
        en: "Local Time",
        cn: "当地时间",
    },
    {
        key: "Dashboard_Widget_SiteLocator_Title",
        en: "Site Locator",
        cn: "网站定位器",
    },
    {
        key: "Dashboard_Widget_MeteringDataMonitoring_Title",
        en: "Metering Data Monitoring",
        cn: "计量数据监控",
    },
    {
        key: "Dashboard_Widget_PeakMonitoring_Title",
        en: "Peak Monitoring",
        cn: "峰值监测",
    },
    {
        key: "Dashboard_Widget_PowerDemand_Title",
        en: "Power Demand",
        cn: "电力需求",
    },
    {
        key: "Dashboard_Widget_PowerFactor_Title",
        en: "Power Factor",
        cn: "功率因数",
    },
    {
        key: "Dashboard_Widget_PowerForecasting_Title",
        en: "Power Forecasting",
        cn: "功率预测",
    },
    {
        key: "Dashboard_Widget_PowerGeneration_Title",
        en: "Power Generation",
        cn: "发电量",
    },
    {
        key: "Dashboard_Widget_PUETrend_Title",
        en: "PUE Trend",
        cn: "PUE趋势",
    },
    {
        key: "Dashboard_Widget_RealTimeCurrents_Title",
        en: "Real Time Currents",
        cn: "实时电流",
    },
    {
        key: "Dashboard_Widget_RealTimePower_Title",
        en: "Real Time Power",
        cn: "实时功率",
    },
    {
        key: "Dashboard_Widget_RealTimeVoltage_Title",
        en: "Real Time Voltage",
        cn: "实时电压",
    },
    {
        key: "Dashboard_Widget_ServiceActivities_Title",
        en: "Service Activities",
        cn: "服务活动",
    },
    {
        key: "Dashboard_Widget_ServiceActivitiesOverview_Title",
        en: "Service Activities Overview",
        cn: "服务活动概述",
    },
    {
        key: "Dashboard_Widget_RealTimeMetering_Title",
        en: "Real Time Metering",
        cn: "实时计量",
    },
    {
        key: "Dashboard_Widget_PUEMonitor_Title",
        en: "PUE Monitor",
        cn: "PUE监控器",
    },
    {
        key: "Dashboard_Widget_States_and_Events_Title",
        en: "States and Counters",
        cn: "状态和计数器",
    },
    {
        key: "Dashboard_Widget_TotalHistoricEnergyData_Title",
        en: "Total Historic Energy Data",
        cn: "总历史能源数据",
    },
    {
        key: "Dashboard_Widget_ArcGuard_Title",
        en: "Arc Guard",
        cn: "弧光保护",
    },
    {
        key: "Dashboard_Widget_ArcGuardCSU2_Title",
        en: "Arc Guard-CSU2",
        cn: "弧光保护-CSU2",
    },
    {
        key: "Dashboard_Widget_TruOneParameters_Title",
        en: "ATS Parameters",
        cn: "ATS参数",
    },
    {
        key: "Dashboard_Widget_ATSTransferTime_Title",
        en: "ATS Transfer Time",
        cn: "ATS切换时间",
    },
    {
        key: "Dashboard_Widget_EnergyAuditSummary_Title",
        en: "Energy Audit Summary",
        cn: "能源审计摘要",
    },
    {
        key: "Dashboard_Widget_EnergyCostComparison_Title",
        en: "Energy Cost Comparison",
        cn: "能源成本比较",
    },
    {
        key: "Dashboard_Widget_EnvironmentalData_Title",
        en: "Environmental Data",
        cn: "环境数据",
    },
    {
        key: "Dashboard_Widget_PerformanceIndicator_Title",
        en: "Performance Indicator",
        cn: "绩效指标",
    },
    {
        key: "Dashboard_Widget_InputDataCalculation_Title",
        en: "Input Data Calculation",
        cn: "输入数据计算",
    },
    {
        key: "Dashboard_Widget_PowerQualityTHD_Title",
        en: "Power Quality - THD",
        cn: "电能质量THD",
    },
    {
        key: "Dashboard_Widget_EnergyData_Title",
        en: "Energy Data",
        cn: "能源数据",
    },
    {
        key: "Dashboard_Widget_GroupRealTimePower_Title",
        en: "Group Real Time Power",
        cn: "组实时电源",
    },
    {
        key: "Dashboard_Widget_HistoricDataMetering_Title",
        en: "Historic Data Metering",
        cn: "历史数据计量",
    },
    {
        key: "Dashboard_Widget_PowerQualityVoltage_Title",
        en: "Power Quality - Voltage",
        cn: "电能质量-电压",
    },
    {
        key: "Dashboard_Widget_EnergyDataComparison_Title",
        en: "Energy Data Comparison",
        cn: "能源数据比较",
    },
    {
        key: "Dashboard_Widget_groupRealTimeCurrent_Title",
        en: "Group Real Time Current",
        cn: "组实时电流",
    },
    {
        key: "Dashboard_Widget_groupRealTimeVoltage_Title",
        en: "Group Real Time Voltage",
        cn: "组实时电压",
    },
    {
        key: "Overview_Widget_Health_overview",
        en: "Health overview",
        cn: "健康概述",
    },
    {
        key: "Overview_Widget_Health_analysis",
        en: "Health analysis",
        cn: "健康分析",
    },
    {
        key: "Overview_Widget_Monitoring_data",
        en: "Monitoring data",
        cn: "监控数据",
    },
    {key: "Overview_Widget_Operations", en: "Operations", cn: "运作方式"},
    {
        key: "Overview_Widget_Remaining_life_trend",
        en: "Remaining life trend",
        cn: "剩余生命趋势",
    },
    {
        key: "Overview_Widget_Temperature_data_trend",
        en: "Temperature data trend",
        cn: "温度数据趋势",
    },
    {
        key: "Overview_Widget_Mechanical_data_trend",
        en: "Mechanical data trend",
        cn: "机械数据趋势",
    },
    {
        key: "Overview_Widget_Breaker_operations",
        en: "Breaker operations",
        cn: "断路器操作",
    },
    {
        key: "Dashboard_Widget_GroupRealTimeMetering_Title",
        en: "Group Real Time Metering",
        cn: "组实时计量",
    },
    {
        key: "Dashboard_Widget_multipleSiteLocator_Title",
        en: "Multiple Site Locator",
        cn: "多网站定位器",
    },
    {
        key: "Total_facility_group",
        en: "Total facility group",
        cn: "总设备组",
    },
    {key: "Subtract_group", en: "Subtract group", cn: "减组"},
    {key: "Period", en: "Period", cn: "期"},
    {
        key: "Compare_to_previous_period",
        en: "Compare to previous period",
        cn: "与上期比较",
    },
    {key: "Asset", en: "Asset", cn: "资产"},
    {key: "Input", en: "Input", cn: "输入"},
    {key: "Group", en: "Group", cn: "组"},
    {key: "Compare_Group", en: "Compare group", cn: "比较组"},
    {key: "Parameter", en: "Parameter", cn: "参数"},
    {key: "Operation", en: "Operation", cn: "操作方式"},
    {
        key: "Show_contractual_power",
        en: "Show contractual power",
        cn: "显示合同功率",
    },
    {key: "Manufacturer", en: "Manufacturer", cn: "制造商"},
    {key: "Asset_class", en: "Asset class", cn: "资产类别"},
    {key: "Type", en: "Type", cn: "类型"},
    {key: "Event_type", en: "Event type", cn: "事件类型"},
    {key: "Device", en: "Asset", cn: "资产"},
    {key: "Measure", en: "Measure", cn: "测量"},
    {key: "Status", en: "Status", cn: "状态"},
    {key: "Location", en: "LOCATION", cn: "位置"},
    {key: "User", en: "User", cn: "用户"},
    {key: "Asset_Classes", en: "ASSET CLASSES", cn: "资产类别"},
    {key: "Downtime", en: "DOWNTIME", cn: "停机时间"},
    {key: "Due_date", en: "DUE DATE", cn: "截止日期"},
    {key: "warning", en: "warning", cn: "警告"},
    {key: "Planned_service", en: "Planned service", cn: "计划服务"},
    {key: "Current_year", en: "Completed this year", cn: "今年"},
    {key: "Current_month", en: "Current month", cn: "当月"},
    {key: "Item", en: "Groups", cn: "组"},
    {key: "Serial_number", en: "Serial number", cn: "序列号"},
    {key: "Service_User", en: "USER", cn: "用户"},
    {key: "Service_Status", en: "STATUS", cn: "状态"},
    {key: "Voltage_type", en: "Voltage type", cn: "电压类型"},
    {key: "Connection_status", en: "Connection status", cn: "连接状态"},
    {
        key: "Explore_AllEquipment_Page_Title",
        en: "Explore: All equipment",
        cn: "探索：所有设备",
    },
    {key: "allAssetsName", en: "NAME", cn: "名称"},
    {key: "allAssetsManufacturer", en: "MANUFACTURER", cn: "制造商"},
    {key: "allAssetsSerialNumber", en: "SERIAL NUMBER", cn: "序列号"},
    {
        key: "allAssetsHealthIndex",
        en: "HEALTH INDEX (%)",
        cn: "健康指数（％）",
    },
    {key: "Overview", en: "Overview", cn: "总览"},
    {key: "Watchers", en: "Watchers", cn: "观察者"},
    {key: "Events", en: "Events", cn: "事件"},
    {key: "Maintenence", en: "Maintenance", cn: "维护"},
    {key: "Condition", en: "CONDITION", cn: "状况"},
    {key: "Connection", en: "CONNECTION", cn: "连接"},
    {key: "Class", en: "CLASS", cn: "类"},
    {key: "Model", en: "MODEL", cn: "模型"},
    {
        key: "monitoring_not_supported",
        en: "You cannot enable monitoring on this asset because it's not supported.",
        cn: "您无法启用对此资产的监控，因为它不受支持。",
    },
    {key: "Not_Monitored", en: "Not Monitored", cn: "不受监控"},
    {key: "Offline", en: "Offline", cn: "离线"},
    {
        key: "Error_occurred",
        en: "Error occurred while loading the page",
        cn: "加载页面时发生错误",
    },
    {
        key: "No_Equipment",
        en: "No Equipment for the plant",
        cn: "没有工厂设备",
    },
    {key: "Status", en: "STATUS", cn: "状态"},
    {key: "Device_events", en: "Asset events", cn: "资产事件"},
    {
        key: "Connectivity_events",
        en: "Connectivity events",
        cn: "通讯事件",
    },
    {key: "Custom_alerts", en: "Custom alerts", cn: "自定义提醒"},
    {key: "Health_warnings", en: "Health warnings", cn: "健康警告"},
    {
        key: "Explore_AllEquipment_Detail_Overview_Widget_CircuitBreakerSummary_Title",
        en: "Circuit Breaker Summary",
        cn: "断路器摘要",
    },
    {
        key: "Explore_AllEquipment_Detail_Overview_Widget_PowerData_Title",
        en: "Power Data",
        cn: "电力数据",
    },
    {
        key: "Explore_AllEquipment_Detail_Overview_Widget_EnvironmentalData_Title",
        en: "Environmental Data",
        cn: "环境数据",
    },
    {
        key: "Explore_AllEquipment_Detail_Overview_Widget_EnvironmentalData_Temperature",
        en: "Temperature (°C)",
        cn: "温度（°C）",
    },
    {
        key: "Explore_AllEquipment_Detail_Overview_Widget_EnvironmentalData_Humidity",
        en: "Humidity (%)",
        cn: "湿度％",
    },
    {
        key: "Explore_AllEquipment_Detail_Overview_Widget_MaintenancePrediction_Title",
        en: "Health prediction",
        cn: "健康预测",
    },
    {
        key: "Explore_AllEquipment_Detail_Overview_Widget_MaintenancePrediction_LastMaintenance",
        en: "Last maintenance",
        cn: "最后维护",
    },
    {
        key: "Explore_AllEquipment_Detail_Overview_Widget_MaintenancePrediction_NextMaintenance",
        en: "Next maintenance",
        cn: "下次维护",
    },
    {
        key: "Explore_AllEquipment_Detail_Overview_Widget_MaintenancePrediction_NA",
        en: "N.A.",
        cn: "不适用",
    },
    {
        key: "Explore_AllEquipment_Detail_Overview_Widget_CurrentAndTemperatureTrends_Title",
        en: "Current & temperature trends",
        cn: "电流和温度趋势",
    },
    {
        key: "Explore_AllEquipment_Detail_Overview_Widget_EnvironmentalData_Vibration",
        en: "Vibration",
        cn: "振动",
    },
    {
        key: "Explore_AllEquipment_Detail_Overview_Widget_EnvironmentalData_Corrosion",
        en: "Corrosion",
        cn: "腐蚀",
    },
    {
        key: "Explore_AllEquipment_Detail_Overview_Widget_EnvironmentalData_DustLevel",
        en: "Dust level",
        cn: "粉尘密度",
    },
    {
        key: "Explore_AllEquipment_Detail_Events_Title",
        en: "Asset events",
        cn: "资产事件",
    },
    {
        key: "Confirm_Events_Action",
        en: "This alert can be modified only by creator",
        cn: "此警报只能由创建者修改",
    },
    {key: "Ok_Events_Action", en: "OK", cn: "好"},
    {
        key: "Explore_AllEquipment_Detail_AlertCondition_Title",
        en: "Asset alert condition",
        cn: "资产警报条件",
    },
    {
        key: "Explore_AllEquipment_Detail_Maintenance_Title",
        en: "Asset service data",
        cn: "资产服务数据",
    },
    {
        key: "Explore_AllEquipment_Detail_Connectivity_Title",
        en: "Connectivity",
        cn: "连接性",
    },
    {
        key: "Explore_AllEquipment_Detail_Information_AssetInformation_Title",
        en: "Asset information",
        cn: "资产信息",
    },
    {
        key: "Explore_AllEquipment_Detail_Information_ElectronicDevice_Title",
        en: "Electronic asset",
        cn: "电子资产",
    },
    {
        key: "Explore_AllEquipment_Detail_Information_LifeCycleData_Title",
        en: "Life cycle data",
        cn: "生命周期数据",
    },
    {key: "CB_tag_name", en: "CB tag name", cn: "CB标签名称"},
    {key: "Nominal_current", en: "Nominal current", cn: "额定电流"},
    {key: "Nominal_voltage", en: "Nominal voltage", cn: "额定电压"},
    {key: "Serial_number", en: "Serial number", cn: "序列号"},
    {key: "Device_ID", en: "Asset ID", cn: "资产编号"},
    {key: "Manufacturer", en: "Manufacturer", cn: "制造商"},
    {key: "InstallationId", en: "InstallationId", cn: "安装ID"},
    {key: "Number_of_poles", en: "Number of poles", cn: "极数"},
    {key: "CB_serial_number", en: "CB serial number", cn: "CB序列号"},
    {key: "CB_type", en: "CB type", cn: "CB类型"},
    {key: "Primary_voltage", en: "Primary voltage", cn: "一次电压"},
    {key: "Product_execution", en: "Product execution", cn: "产品执行"},
    {key: "Tag_name", en: "Tag name", cn: "标签名"},
    {key: "Model", en: "Model", cn: "模型"},
    {key: "Application", en: "Application", cn: "应用"},
    {key: "Rating", en: "Rating", cn: "评分"},
    {key: "siteId", en: "siteId", cn: "站点ID"},
    {key: "Trip_unit_type", en: "Trip unit type", cn: "脱扣器类型"},
    {
        key: "Mainboard_software_version",
        en: "Mainboard software version",
        cn: "主板软件版本",
    },
    {
        key: "Mainboard_serial_number",
        en: "Mainboard serial number",
        cn: "主板序列号",
    },
    {
        key: "Trip_unit_software_version",
        en: "Trip unit software version",
        cn: "脱扣器软件版本",
    },
    {
        key: "Trip_unit_serial_number",
        en: "Trip unit serial number",
        cn: "脱扣器序列号",
    },
    {
        key: "EkipComHubSoftwareVersion",
        en: "EkipComHubSoftwareVersion",
        cn: "EkipComHub软件版本",
    },
    {key: "Device_type", en: "Asset type", cn: "资产类型"},
    {key: "Modbus_address", en: "Modbus address", cn: "Modbus地址"},
    {key: "Commission_date", en: "Commission date", cn: "调试日期"},
    {key: "Version", en: "Version", cn: "版"},
    {key: "Firmware", en: "Firmware", cn: "固件"},
    {key: "Installation_date", en: "Installation date", cn: "安装日期"},
    {key: "Manual_operation", en: "Manual operation", cn: "手动操作"},
    {key: "Total_operations", en: "Total operations", cn: "总操作次数"},
    {key: "Number_of_trips", en: "Number of trips", cn: "脱扣次数"},
    {key: "Contact_wear", en: "Contact wear", cn: "触点磨损"},
    {
        key: "Device_Hub_Serial_Number",
        en: "Asset hub serial number",
        cn: "资产中心序列号",
    },
    {key: "Plant_Id", en: "Plant Id", cn: "工厂ID"},
    {
        key: "Host_Serial_Number",
        en: "Host serial number",
        cn: "主机序列号",
    },
    {key: "Is_Main", en: "Is main", cn: "是主电网设备"},
    {key: "Is_Generator", en: "Is generator", cn: "是发电机"},
    {key: "Notes_Key", en: "Notes", cn: "笔记"},
    {key: "Installation_Date", en: "Installation date", cn: "安装日期"},
    {key: "Is_CB_Linked", en: "Is CB linked", cn: "CB是否链接"},
    {
        key: "CB_Installation_Date",
        en: "CB installation date",
        cn: "断路器安装日期",
    },
    {key: "CB_Version", en: "CB version", cn: "CB版本"},
    {key: "CB_Family", en: "CB family", cn: "CB家族"},
    {key: "Standard_Reference", en: "Standard reference", cn: "标准参考"},
    {key: "CB_Type", en: "CB type", cn: "CB类型"},
    {key: "CB_Poles", en: "CB poles", cn: "CB极数"},
    {
        key: "Additional_Number_Of_Operations",
        en: "Additional number of operations",
        cn: "须附加操作次数",
    },
    {
        key: "Contact_Wear_T1_Percentage",
        en: "Contact wear T1 percentage",
        cn: "触点磨损T1%",
    },
    {
        key: "Contact_Wear_T2_Percentage",
        en: "Contact wear T2 percentage",
        cn: "触点磨损T2%",
    },
    {
        key: "Environmental_Preset_Id",
        en: "Environmental preset Id",
        cn: "环境预设ID",
    },
    {key: "Equipment_Status", en: "Equipment status", cn: "设备状态"},
    {key: "Slave_Id", en: "Slave id", cn: "从站ID"},
    {key: "Device_Name", en: "Asset name", cn: "资产名称"},
    {key: "Device_Type_Code", en: "Asset type code", cn: "资产类型代码"},
    {
        key: "Is_Main_Enabled",
        en: "Is main enabled",
        cn: "主电网设备是否启用",
    },
    {
        key: "Is_Generator_Enabled",
        en: "Is generator enabled",
        cn: "发电机是否启用",
    },
    {
        key: "Is_Analog_Input_Enabled",
        en: "Is analog input enabled",
        cn: "模拟输入是否启用",
    },
    {
        key: "Is_Current_Enabled",
        en: "Is current enabled",
        cn: "电流是否启用",
    },
    {
        key: "Is_Digital_Input_Enabled",
        en: "Is digital input enabled",
        cn: "启用数字输入",
    },
    {
        key: "Is_Digital_Output_Enabled",
        en: "Is digital output enabled",
        cn: "启用数字输出",
    },
    {key: "Is_Energy_Enabled", en: "Is energy enabled", cn: "启用能源"},
    {
        key: "Is_Network_Analyzer_Enabled",
        en: "Is network analyzer enabled",
        cn: "电网分析是否启用",
    },
    {key: "Is_Power_Enabled", en: "Is power enabled", cn: "功率是否启用"},
    {
        key: "Is_Power_Factor_Enabled",
        en: "Is power factor enabled",
        cn: "启用功率因数",
    },
    {
        key: "Is_Voltage_Enabled",
        en: "Is voltage enabled",
        cn: "电压是否启用",
    },
    {
        key: "Is_Advanced_Predictive_Maintenance",
        en: "Is advanced predictive maintenance",
        cn: "预测性维护是否启用",
    },
    {
        key: "Is_Transfer_Switch_Enabled",
        en: "Is transfer switch enabled",
        cn: "转换开关是否启用",
    },
    {
        key: "Is_Current_Sensing_Enabled",
        en: "Is current sensing enabled",
        cn: "电流感应是否启用",
    },
    {key: "CB_Status", en: "CB status", cn: "开关状态"},
    {key: "State_Input1", en: "State input1", cn: "状态输入1"},
    {key: "State_Input2", en: "State input2", cn: "状态输入2"},
    {key: "State_Input3", en: "State input3", cn: "状态输入3"},
    {key: "State_Input4", en: "State input4", cn: "状态输入4"},
    {key: "State_Input5", en: "State input5", cn: "状态输入5"},
    {key: "State_Input6", en: "State input6", cn: "状态输入6"},
    {key: "State_Input7", en: "State input7", cn: "状态输入7"},
    {key: "State_Input8", en: "State input8", cn: "状态输入8"},
    {key: "State_Input9", en: "State input9", cn: "状态输入9"},
    {key: "State_Input10", en: "State input10", cn: "状态输入10"},
    {key: "State_Input11", en: "State input11", cn: "状态输入11"},
    {key: "CB_Pos", en: "CB pos", cn: "CB极数"},
    {key: "Operative_Mode", en: "Operative mode", cn: "操作模式"},
    {key: "Any_Alarm", en: "Any alarm", cn: "任意报警"},
    {key: "Any_Trip_Alarm", en: "Any trip alarm", cn: "任意脱扣报警"},
    {key: "Name_Signalling_TCP", en: "Tag Name", cn: "标签名"},
    {key: "TagName_In1", en: "Tag name in1", cn: "标签名称in1"},
    {key: "TagName_In2", en: "Tag name in2", cn: "标签名称in2"},
    {key: "TagName_In3", en: "Tag name in3", cn: "标签名称in3"},
    {key: "TagName_In4", en: "Tag name in4", cn: "标签名称in4"},
    {key: "TagName_In5", en: "Tag name in5", cn: "标签名称in5"},
    {key: "TagName_In6", en: "Tag name in6", cn: "标签名称in6"},
    {key: "TagName_In7", en: "Tag name in7", cn: "标签名称in7"},
    {key: "TagName_In8", en: "Tag name in8", cn: "标签名称in8"},
    {key: "TagName_In9", en: "Tag name in9", cn: "标签名称in9"},
    {key: "TagName_In10", en: "Tag name in10", cn: "标签名称in10"},
    {key: "TagName_In11", en: "Tag name in11", cn: "标签名称in11"},
    {key: "Pole_Number", en: "Pole number", cn: "极数"},
    {
        key: "Ekip_Com_Hub_Software_Version",
        en: "Ekip com hub software version",
        cn: "Ekip com hub软件版本",
    },
    {
        key: "Ekip_Com_Hub_Software_Version_Description",
        en: "Ekip com hub software version description",
        cn: "Ekip com hub软件版本说明",
    },
    {
        key: "Switch_Installation_Date",
        en: "Switch installation date",
        cn: "开关安装日期",
    },
    {key: "Device_Mode", en: "Asset mode", cn: "资产模式"},
    {key: "L1_Status", en: "L1 status", cn: "L1状态"},
    {key: "L2_Status", en: "L2 status", cn: "L2状态"},
    {key: "Type_Code", en: "Type code", cn: "类型代码"},
    {key: "Type_Designation", en: "Type designation", cn: "型号名称"},
    {key: "Firmware_Version", en: "Firmware version", cn: "固件版本"},
    {key: "Phase_Configuration", en: "Phase configuration", cn: "相配置"},
    {
        key: "Number_Of_Operations",
        en: "Number of operations",
        cn: "操作次数",
    },
    {key: "Out_V1", en: "Out V1", cn: "输出V1"},
    {key: "Out_V2", en: "Out V2", cn: "输出V2"},
    {key: "Out_V3", en: "Out V3", cn: "输出V3"},
    {key: "Batt_Temp", en: "Batt temp", cn: "电池温度"},
    {key: "Frequency_Key", en: "Frequency", cn: "频率"},
    {key: "CM_Error_Summary", en: "CM error summary", cn: "CM错误摘要"},
    {
        key: "CM_Restart_Delay",
        en: "CM restart delay",
        cn: "CM重新启动延迟",
    },
    {key: "CM_Relay1", en: "CM relay1", cn: "CM继电器1"},
    {key: "CM_Relay2", en: "CM relay2", cn: "CM继电器2"},
    {key: "CM_Relay3", en: "CM relay3", cn: "CM继电器3"},
    {key: "CM_Input_Y1", en: "CM input Y1", cn: "CM输入Y1"},
    {key: "CM_Input_Y2", en: "CM input Y2", cn: "CM输入Y2"},
    {key: "CM_Input_Y3", en: "CM input Y3", cn: "CM输入Y3"},
    {key: "Last_Maintenance", en: "Last maintenance", cn: "上次维护"},
    {
        key: "Number_Of_Extension_Units",
        en: "Number of extension units",
        cn: "扩展单元数",
    },
    {key: "External_HMI", en: "External HMI", cn: "外部人机界面"},
    {
        key: "Electrical_Life_Percentage",
        en: "Electrical life percentage",
        cn: "电气寿命百分比",
    },
    {
        key: "Installed_Modules",
        en: "Installed modules",
        cn: "已安装的模块",
    },
    {
        key: "TVOC_Trip_Detector_Inputs",
        en: "TVOC trip detector inputs",
        cn: "TVOC脱扣检测输入",
    },
    {key: "Sensors_key", en: "Sensors", cn: "传感器"},
    {key: "PCS100_Status", en: "PCS100 status", cn: "PCS100状态"},
    {
        key: "PCS100_Warning_Indication",
        en: "PCS100 warning indication",
        cn: "PCS100警告指示",
    },
    {
        key: "PCS100_Inhibit_Indication",
        en: "PCS100 inhibit indication",
        cn: "PCS100禁止指示",
    },
    {
        key: "PCS100_Active_Event_Code",
        en: "PCS100 active event code",
        cn: "PCS100事件代码",
    },
    {
        key: "PCS100_Product_Code",
        en: "PCS100 product code",
        cn: "PCS100产品代码",
    },
    {
        key: "PCS100_Rated_Current",
        en: "PCS100 rated current",
        cn: "PCS100额定电流",
    },
    {
        key: "PCS100_Rated_Voltage",
        en: "PCS100 rated voltage",
        cn: "PCS100额定电压",
    },
    {
        key: "PCS100_Rated_Frequency",
        en: "PCS100 rated frequency",
        cn: "PCS100额定频率",
    },
    {
        key: "PCS100_Device_Events",
        en: "PCS100 asset events",
        cn: "PCS100资产事件",
    },
    {
        key: "Transfer_Time_Threshold",
        en: "Transfer time threshold",
        cn: "传输时间阈值（毫秒）",
    },
    {key: "Is_System_Trip", en: "Is system trip", cn: "是系统脱扣"},
    {key: "Is_System_Warning", en: "Is system warning", cn: "是系统警告"},
    {key: "Is_System_Error", en: "Is system error", cn: "是系统错误"},
    {key: "Sensing_Infos", en: "Sensing infos", cn: "传感信息"},
    {key: "Sensing_Warnings", en: "Sensing warnings", cn: "传感器警报"},
    {key: "Sensing_Errors", en: "Sensing errors", cn: "传感器错误"},
    {
        key: "Installed_Ekip_Com_Hub_Serial_Number",
        en: "Installed ekip com hub serial number",
        cn: "已安装的ekip com hub序列号",
    },
    {
        key: "Software_Version_Signalling_TCP",
        en: "Software version signalling TCP",
        cn: "软件版本TCP",
    },
    {key: "SW_Ver", en: "SW version", cn: "软件版本"},
    {
        key: "Trip_Unit_SN",
        en: "Trip Unit Serial Number",
        cn: "脱扣单元序列号",
    },
    {
        key: "Total_Operations_Input1",
        en: "Total operations input 1",
        cn: "总计操作输入1",
    },
    {
        key: "Total_Operations_Input2",
        en: "Total operations input 2",
        cn: "总计操作输入2",
    },
    {
        key: "Total_Operations_Input3",
        en: "Total operations input 3",
        cn: "总计操作输入3",
    },
    {
        key: "Total_Operations_Input4",
        en: "Total operations input 4",
        cn: "总计操作输入4",
    },
    {
        key: "Total_Operations_Input5",
        en: "Total operations input 5",
        cn: "总计操作输入5",
    },
    {
        key: "Total_Operations_Input6",
        en: "Total operations input 6",
        cn: "总计操作输入6",
    },
    {
        key: "Total_Operations_Input7",
        en: "Total operations input 7",
        cn: "总计操作输入7",
    },
    {
        key: "Total_Operations_Input8",
        en: "Total operations input 8",
        cn: "总计操作输入8",
    },
    {
        key: "Total_Operations_Input9",
        en: "Total operations input 9",
        cn: "总计操作输入9",
    },
    {
        key: "Total_Operations_Input10",
        en: "Total operations input 10",
        cn: "总计操作输入10",
    },
    {
        key: "Total_Operations_Input11",
        en: "Total operations input 11",
        cn: "总计操作输入11",
    },
    {key: "Temp_L1", en: "L1 temperature", cn: "L1温度"},
    {key: "Temp_L2", en: "L2 temperature", cn: "L2温度"},
    {key: "Temp_L3", en: "L3 temperature", cn: "L3温度"},
    {key: "Temp_N", en: "N temperature", cn: "N相温度"},
    {key: "Temp_Int", en: "ATS internal temperature", cn: "ATS内部温度"},
    {
        key: "N_Load_Transf",
        en: "Number of load transfers",
        cn: "负载切换次数",
    },
    {key: "Transf_Time", en: "Transfer time", cn: "切换时间"},
    {key: "CM_TripR", en: "CM trip r", cn: "CM脱扣"},
    {
        key: "CM_Freq_Value_Invalid",
        en: "CM freq value invalid",
        cn: "CM频率值无效",
    },
    {
        key: "Display_Temperature",
        en: "Display temperature",
        cn: "显示温度",
    },
    {
        key: "Source_Fail_Transfers",
        en: "Source fail transfers",
        cn: "源故障切换",
    },
    {key: "Energized_Days", en: "Energized days", cn: "电能时间"},
    {
        key: "S1_Available_Minutes",
        en: "S1 available minutes",
        cn: "S1可用分钟",
    },
    {key: "S1_Total_Minutes", en: "S1 total minutes", cn: "S1总分钟"},
    {
        key: "S2_Available_Minutes",
        en: "S2 available minutes",
        cn: "S2可用分钟",
    },
    {key: "S2_Total_Minutes", en: "S2 total minutes", cn: "S2总分钟"},
    {
        key: "Generator_Last_Start",
        en: "Generator last start",
        cn: "发电机上次启动",
    },
    {
        key: "Generator_Start_Seconds",
        en: "Generator start seconds",
        cn: "发电机启动秒数",
    },
    {
        key: "In_Phase_Time_Seconds",
        en: "In phase time seconds",
        cn: "同相秒数",
    },
    {key: "Asset_identifier", en: " Asset identifier:", cn: "资产标识符"},
    {key: "Installation_date", en: "Installation date:", cn: "安装日期"},
    {key: "Primary_voltage", en: "Primary voltage:", cn: "一次电压"},
    {
        key: "Environmental_preset",
        en: "Environmental preset:",
        cn: "环境预设",
    },
    {
        key: "Go_to_settings_to_manage_the_environment_present",
        en: "Go to settings to manage the environmental data",
        cn: "设置环境数据",
    },
    {key: "Name", en: "Name", cn: "名称"},
    {key: "Note", en: "Note", cn: "注释"},
    {key: "Save_information", en: "Save information", cn: "保存"},
    {key: "Analog_Inputs", en: "Analog Inputs", cn: "模拟输入"},
    {key: "Digital_Outputs", en: "Digital Outputs", cn: "数字输出"},
    {key: "Digital_Inputs", en: "Digital Inputs", cn: "数字输入"},
    {key: "Edit", en: "Edit", cn: "编辑"},
    {key: "Asset_information", en: "Asset information", cn: "资产信息"},
    {key: "Cancel", en: "Cancel", cn: "取消"},
    {key: "Function", en: "Function", cn: "功能"},
    {
        key: "Asset_serial_number",
        en: "Asset serial number",
        cn: "资产序列号",
    },
    {key: "Asset_version", en: "Asset version", cn: "资产版本"},
    {key: "Asset_family", en: "Asset family", cn: "资产分类"},
    {key: "Standard_reference", en: "Standard reference", cn: "标准参考"},
    {key: "Asset_type", en: "Asset type", cn: "资产类型"},
    {key: "Asset_poles", en: "Asset poles", cn: "资产极数"},
    {
        key: "Additional_number_of_operations",
        en: "Additional number of operations",
        cn: "须附加操作次数",
    },
    {
        key: "Contact_wear_T1",
        en: "Contact wear (T1)",
        cn: "触点磨损（T1）",
    },
    {key: "Asset_linked", en: "Asset linked", cn: "资产关联"},
    {
        key: "Transfer_time_threshold",
        en: "Transfer time threshold (ms):",
        cn: "传输时间阈值（毫秒）",
    },
    {key: "Add_time_slot", en: "Add time slot", cn: "添加时间段"},
    {key: "Pass_ownership", en: "Pass ownership", cn: "通过所有权"},
    {
        key: "Set_for_every_Weekday",
        en: "Set for every Weekday",
        cn: "每个工作日设置",
    },
    {
        key: "Set_for_the_Weekend",
        en: "Set for the Weekend",
        cn: "为周末设置",
    },
    {
        key: "Asset_documentation",
        en: "Asset documentation",
        cn: "资产文件",
    },
    {key: "add", en: "add", cn: "增加"},
    {key: "Add_document", en: " Add document", cn: "新增文件"},
    {key: "Events", en: "Events:", cn: "事件"},
    {key: "All_events", en: "All events", cn: "所有事件"},
    {
        key: "Add_a_new_alert_on_the_Alerts_page",
        en: "Add a new alert on the Alerts page",
        cn: "添加新建警报",
    },
    {
        key: "The_event_list_is_empty",
        en: "The event list is empty",
        cn: "事件列表为空",
    },
    {key: "close", en: "close", cn: "关"},
    {
        key: "Select_Asset_Placeholder",
        en: "Select asset...",
        cn: "选择资产",
    },
    {key: "Maintenance", en: "Maintenance", cn: "维护"},
    {key: "Asset", en: "Asset", cn: "资产"},
    {key: "Due_date", en: "Due date", cn: "截止日期"},
    {key: "Description", en: "Description", cn: "描述"},
    {key: "Priority", en: "Priority:", cn: "优先"},
    {key: "warning", en: "warning", cn: "警告"},
    {key: "Assigned_User", en: "Assigned User", cn: "分配的用户"},
    {key: "Change_User", en: "Change User", cn: "变更用户"},
    {
        key: "Execute_maintenance",
        en: "Execute maintenance",
        cn: "执行维护",
    },
    {key: "Execution_date", en: "Execution date", cn: "执行日期"},
    {key: "Save_Maintenance", en: "Save maintenance", cn: "保存"},
    {
        key: "Save_and_close_maintenance",
        en: "Save and close maintenance",
        cn: "保存并关闭",
    },
    {key: "asset", en: "ASSET", cn: "资产"},
    {
        key: "Maintenance_created",
        en: "Maintenance created successfully",
        cn: "维护创建成功",
    },
    {
        key: "Maintenance_updated",
        en: "Maintenance updated successfully",
        cn: "维护成功更新",
    },
    {key: "Assign_user", en: "Assign User", cn: "分配用户"},
    {
        key: "Maintenance_deleted",
        en: "Maintenance deleted successfully",
        cn: "维护已成功删除",
    },
    {
        key: "dueDateErrorMsg",
        en: "Due date is required",
        cn: "到期日期为必填项",
    },
    {
        key: "descriptionErrorMsg",
        en: "Description is required",
        cn: "需要描述",
    },
    {
        key: "executionDateErrorMsg",
        en: "Execution date required",
        cn: "需要执行日期",
    },
    {key: "AssetErrorMsg", en: "Select asset", cn: "选择资产"},
    {
        key: "dueDateMinDateError",
        en: "Due date cannot be less than current date",
        cn: "到期日期不能小于当前日期",
    },
    {key: "assignErrormsg", en: "No user assigned", cn: "未分配用户"},
    {
        key: "descriptionLengthMsg",
        en: "Description length should be less than or equal to 1000 characters",
        cn: "描述长度应小于或等于1000个字符",
    },
    {key: "Acknowledge_date", en: "Acknowledge date", cn: "确认日期"},
    {key: "Acknowledge_Notes", en: "Acknowledge notes", cn: "致谢笔记"},
    {key: "New", en: "New", cn: "新建"},
    {key: "Settings", en: "Settings: ", cn: "设置"},
    {key: "Documentation", en: "Documentation", cn: "文档"},
    {key: "Energy", en: "Energy", cn: "电能(kWh)"},
    {key: "Utility", en: "Utility", cn: "设施"},
    {key: "Billing", en: "Billing", cn: "费用"},
    {key: "Currency", en: "Currency:", cn: "币种"},
    {
        key: "Site_generation_capacity",
        en: "Site generation capacity:",
        cn: "发电容量",
    },
    {
        key: "Default_Energy_Price",
        en: "Default energy price (per kWh)",
        cn: "默认电费价格（每kWh）",
    },
    {key: "kWp", en: "kWp", cn: "kWp"},
    {key: "Contractual_power", en: "Contractual power", cn: "合同功率"},
    {key: "Period", en: "Period", cn: "期"},
    {key: "Default", en: "Default", cn: "默认"},
    {
        key: "From_01/01/2000_and_expires_on_01/01/2100",
        en: "From 01/01/2000 and expires on 01/01/2100",
        cn: "从2000年1月1日开始，到2100年1月1日到期",
    },
    {
        key: "Contractual_Power_(KW)",
        en: "Contractual power (KW)",
        cn: "合同功率（KW）",
    },
    {key: "Day", en: "Day", cn: "天"},
    {key: "kW", en: "kW", cn: "kW"},
    {key: "Default_slot", en: "Default slot", cn: "默认位置"},
    {key: "00:00_23:59", en: "00:00 - 23:59", cn: "00:00 - 23:59"},
    {
        key: "Power_Price_(KWH)",
        en: "Power Price (KWH)",
        cn: "电价（KWH）",
    },
    {key: "Slot_Name", en: " Slot Name", cn: "名称"},
    {key: "No_Data", en: "No Data", cn: "没有数据"},
    {key: "Cost_plan", en: "Cost plan", cn: "成本计划"},
    {key: "Remove", en: "Remove", cn: "删除"},
    {key: "From", en: "From", cn: "从"},
    {key: "and_expires_on", en: "and expires on", cn: "并失效于"},
    {
        key: "Power_Price_(KWH)",
        en: "Power Price (KWH)",
        cn: "电价（KWH）",
    },
    {key: "Plan_name", en: "Plan name", cn: "计划名称"},
    {key: "Planning", en: "Planning", cn: "规划"},
    {key: "Add_special_day", en: "Add special day", cn: "添加特殊的日期"},
    {key: "Time_Slot", en: "Time slot", cn: "时间段"},
    {key: "Slot_Name", en: " Slot name", cn: "名称"},
    {key: "0", en: "00", cn: "00"},
    {key: "to", en: "to", cn: "至"},
    {key: "0:00", en: "0:00:00", cn: "0:00:00"},
    {key: "Add_time_slot", en: "Add time slot", cn: "添加时间段"},
    {
        key: "Remove_special_day",
        en: "Remove special day",
        cn: "删除特殊额日期",
    },
    {
        key: "Set_for_the_Weekend",
        en: "Set for the weekend",
        cn: "为周末设置",
    },
    {
        key: "Set_for_every_Weekday",
        en: "Set for every weekday",
        cn: "每个工作日设置",
    },
    {
        key: "Performance_parameters",
        en: "Performance parameters",
        cn: "性能参数",
    },
    {key: "Parameter", en: "Parameter", cn: "参数"},
    {key: "Unit_of_measure", en: "Unit of measure", cn: "测量单位"},
    {key: "Description", en: "Description", cn: "描述"},
    {key: "Shifts_plan", en: "Shifts plan", cn: "轮班计划"},
    {key: "Team", en: "Team", cn: "组"},
    {key: "Number_of_people", en: "Number of people", cn: "人数"},
    {key: "Team_responsible", en: "Team responsible", cn: "团队负责"},
    {key: "Edit_plan", en: "Edit plan", cn: "修改计划"},
    {key: "Delete_plan", en: "Delete plan", cn: "删除方案"},
    {key: "people", en: "people", cn: "人"},
    {key: "Select_Preset", en: "Select preset...", cn: "选择预设..."},
    {
        key: "ADD_A_CUSTOM_PRESET",
        en: "ADD A CUSTOM PRESET",
        cn: "添加自定义预设",
    },
    {
        key: "Add_custom_preset",
        en: "Add custom preset",
        cn: "添加自定义预设",
    },
    {key: "Preset", en: "Preset", cn: "预设"},
    {key: "Conditions", en: "Conditions", cn: "条件"},
    {key: "Voltage", en: "Voltage", cn: "电压"},
    {key: "Vibration", en: "Vibration", cn: "振动"},
    {key: "Low", en: "Low", cn: "低"},
    {key: "Medium", en: "Medium", cn: "中"},
    {key: "High", en: "High", cn: "高"},
    {key: "Corrosion", en: "Corrosion", cn: "腐蚀"},
    {key: "Dust_level", en: "Dust level", cn: "粉尘级别"},
    {key: "Humidity", en: "Humidity", cn: "湿度"},
    {
        key: "Shore_line_distance",
        en: "Shore line distance (salt level)",
        cn: "岸线距离 (盐含量)",
    },
    {key: "Average_yearly_T", en: "Average yearly T", cn: "年平均温度"},
    {key: "Devices", en: "Assets", cn: "资产"},
    {key: "Active_events", en: "Active events", cn: "活动事件"},
    {key: "Health_index", en: "Health index", cn: "健康指数"},
    {key: "Total_assets", en: "Assets", cn: "资产"},
    {key: "Total_Events", en: "Total events", cn: "总事件"},
    {key: "Current_Year", en: "Current Year", cn: "今年"},
    {
        key: "Service_and_environment",
        en: "Service and environment",
        cn: "服务与环境",
    },
    {key: "Company", en: "Company", cn: "公司"},
    {key: "Surname", en: "Surname", cn: "姓"},
    {key: "Email", en: "Email", cn: "电子邮件"},
    {key: "Phone", en: "Phone", cn: "电话"},
    {key: "Save_contact", en: "Save contact", cn: "保存"},
    {key: "Environmental_data", en: "Environmental data", cn: "环境数据"},
    {
        key: "You_do_not_have_permission_to_access_this_page",
        en: "You don't have permission to access this page",
        cn: "您无权访问此页面",
    },
    {key: "Select", en: "Select", cn: "选择"},
    {key: "Site", en: "Site", cn: "站点"},
    {key: "Site_identifier", en: "Site identifier", cn: "站点识别码"},
    {key: "Site_information", en: "Site information", cn: "站点信息"},
    {key: "Site_name", en: "Site name", cn: "站点名称"},
    {key: "Country", en: "Country", cn: "国家"},
    {key: "Timezone", en: "Timezone", cn: "时区"},
    {key: "Address", en: "Address", cn: "地址"},
    {key: "Post_code", en: "Post code", cn: "邮编"},
    {key: "Location", en: "Location", cn: "位置"},
    {key: "Zone", en: "Zone", cn: "区"},
    {
        key: "Terms_of_service_to_be_approved_by_site_owner",
        en: "Terms of use to be approved by site owner",
        cn: "服务条款应由站点所有者批准",
    },
    {
        key: "Terms_of_service_approved_by_site_owner",
        en: "Terms of use approved by site owner",
        cn: "站点所有者批准的服务条款",
    },
    {key: "Agree", en: "Agree", cn: "同意"},
    {key: "Disagree", en: "Disagree", cn: "不同意"},
    {
        key: "Print_terms_of_service",
        en: "Print terms of use",
        cn: "打印服务条款",
    },
    {key: "Confirm", en: "Confirm", cn: "确认"},
    {key: "copy_api_key", en: "Copy API key", cn: "复制API密钥"},
    {key: "reset_api_key", en: "Reset API key", cn: "重置API密钥"},
    {key: "api_key_document", en: "API Key document", cn: "API密钥文件"},
    {key: "Select_Role", en: "Select role...", cn: "选择角色..."},
    {
        key: "Users_and_groups",
        en: "Users and groups / Users",
        cn: "用户和组",
    },
    {
        key: "You_have_no_permission_to_access_this_page",
        en: "You have no permission to access this page",
        cn: "您无权访问此页面",
    },
    {key: "Send_invitation", en: "Send invitation", cn: "发送邀请"},
    {
        key: "User_limit_exceeded",
        en: "User limit exceeded",
        cn: "用户超出限制",
    },
    {key: "Status", en: "Status", cn: "状态"},
    {key: "Role", en: "Role", cn: "角色"},
    {key: "replay", en: "replay", cn: "重播"},
    {key: "Renew_request", en: "Renew invitation", cn: "续订邀请"},
    {key: "delete", en: "delete", cn: "删除"},
    {key: "Delete_request", en: "Delete invitation", cn: "删除邀请"},
    {key: "Expire_date", en: "Expire date", cn: "失效日期"},
    {key: "school", en: "school", cn: "学校"},
    {key: "Pass_ownership", en: "Pass ownership", cn: "通过所有权"},
    {key: "edit", en: "edit", cn: "编辑"},
    {key: "User", en: "User", cn: "用户"},
    {key: "Contacts", en: "Contacts", cn: "联络人"},
    {key: "Invitation", en: "Invitation", cn: "邀请"},
    {
        key: "you_are_not_authorized_to_perform_this_action",
        en: "You are not authorized to perform this action",
        cn: "您无权执行此操作",
    },
    {
        key: "Insert_Email_Address",
        en: "Insert email address",
        cn: "插入电子邮件地址",
    },
    {key: "Set_User_Role", en: "Set user role", cn: "设定用户角色"},
    {key: "Group_01", en: "Group 01", cn: "组01"},
    {key: "Custom", en: "Custom", cn: "自定义"},
    {key: "Data_Group", en: "Data group", cn: "资料组"},
    {key: "Save_group", en: "Save group", cn: "保存"},
    {key: "Type", en: "Type", cn: "类型"},
    {
        key: "Energy_audit_process",
        en: "Energy audit process",
        cn: "电能审核程序",
    },
    {
        key: "Energy_audit_auxiliary_services",
        en: "Energy audit auxiliary services",
        cn: "电能审计辅助服务",
    },
    {
        key: "Energy_audit_general_services",
        en: "Energy audit general services",
        cn: "电能审计一般服务",
    },
    {
        key: "This_group_can_be_added_to_the_power_forecast.Up_to_5_groups_can_be_added_simultaneously_to_the_service.",
        en: "This group can be added to the power forecast. Up to 5 groups can be added simultaneously to the service.",
        cn: "可以将此组添加到功率预测中。最多可以同时将5个组添加到该服务。",
    },
    {key: "Sum_Substaction", en: "Sum/Substaction", cn: "总和/替代"},
    {key: "Average", en: "Average", cn: "平均"},
    {key: "Max", en: "Max", cn: "最大"},
    {key: "Min", en: "Min", cn: "最小"},
    {key: "Operation", en: "Operation", cn: "操作方式"},
    {key: "Items", en: "Items", cn: "物品"},
    {key: "Set_sum_for_all", en: "Set sum for all", cn: "设置所有加法"},
    {
        key: "Set_subtraction_for_all",
        en: "Set subtraction for all",
        cn: "设置所有减法",
    },
    {key: "Set_none_for_all", en: "Set none for all", cn: "全部不设"},
    {
        key: "Set_measurements_for_all",
        en: "Set measurements for all",
        cn: "设置所有测量",
    },
    {key: "Delete_all_items", en: "Delete all items", cn: "删除所有项目"},
    {key: "Current", en: "Current", cn: "当前"},
    {key: "Power", en: "Power", cn: "功率"},
    {key: "Gas_Volume", en: "Gas volume", cn: "气体容积"},
    {key: "Add_item", en: "Add item", cn: "添加项目"},
    {key: "Summary", en: "Summary", cn: "摘要"},
    {key: "Power_forecast", en: "Power forecast", cn: "功率预测"},
    {key: "Disabled", en: "Disabled", cn: "禁用"},
    {key: "Supported_measures", en: "Supported measures", cn: "支持措施"},
    {key: "Selected", en: "Selected", cn: "已选"},
    {key: "Set_sum", en: "Set sum", cn: "设置加法"},
    {key: "Set_subtraction", en: "Set subtraction", cn: "设置减法"},
    {key: "Set_none", en: "Set none", cn: "不设置"},
    {key: "Set_measurements", en: "Set measurements", cn: "设置测量"},
    {key: "Delete_item", en: "Delete item", cn: "删除项目"},
    {key: "scheduledReports", en: "SCHEDULED REPORTS", cn: "预定报告"},
    {key: "NewReportTask", en: "New Report Task", cn: "新建报告任务"},
    {key: "Generic", en: "Generic", cn: "泛型"},
    {key: "Groups", en: "Groups", cn: "组"},
    {key: "Sensors", en: "Sensors", cn: "传感器"},
    {key: "Assets", en: "Assets", cn: "资产"},
    {key: "Enabled", en: "Enabled", cn: "启用"},
    {
        key: "Power_forecast_enabled",
        en: "Power forecast enabled",
        cn: "启用功率预测",
    },
    {
        key: "Power_forecast_disabled",
        en: "Power forecast disabled",
        cn: "功率预测已禁用",
    },
    {key: "Total_Items", en: "Total Items", cn: "总项目"},
    {
        key: "No_devices_found_in_the_plant",
        en: "No assets found in the plant",
        cn: "工厂中没有资产",
    },
    {
        key: "No_group_found_in_the_plant",
        en: "No group found in the plant",
        cn: "工厂中没有组",
    },
    {
        key: "No_sensors_found_in_the_plant",
        en: "No sensors found in the plant",
        cn: "工厂中没有传感器",
    },
    {key: "Addition", en: "Addition", cn: "添加"},
    {key: "Subtraction", en: "Subtraction", cn: "减法"},
    {key: "None", en: "None", cn: "没有"},
    {key: "Autogenerated", en: "Autogenerated", cn: "自动生成"},
    {
        key: "Group_deleted_successfully",
        en: "Group has been deleted successfully",
        cn: "组已成功删除",
    },
    {
        key: "Group_saved_successfully",
        en: "Group has been saved successfully",
        cn: "组已成功保存",
    },
    {
        key: "Group_updated_successfully",
        en: "Group has been updated successfully",
        cn: "组已成功更新",
    },
    {
        key: "Reports_Downloaded_successfully",
        en: "Report has been downloaded successfully",
        cn: "报告已成功下载",
    },
    {
        key: "No_plant_to_compare",
        en: "No plant found to compare",
        cn: "找不到要比较的工厂",
    },
    {key: "Report_failed", en: "Report failed", cn: "报告失败"},
    {key: "Add_new_group", en: "Add new group", cn: "创建新组"},
    {
        key: "Failed_to_download_the_report",
        en: "Failed to download the report",
        cn: "无法下载报告",
    },
    {
        key: "Something_went_wrong",
        en: "Something went wrong. Please try again.",
        cn: "出问题了。请再试一次",
    },
    {key: "3_Selected", en: "3 Selected", cn: "3 已选择"},
    {key: "Add_user", en: "Add User", cn: "添加用户"},
    {key: "Power_usage", en: "Power usage", cn: "用电量"},
    {
        key: "reportTypeErrorMsg",
        en: "Report type is required",
        cn: "报告类型为必填",
    },
    {
        key: "equipmentErrorMsg",
        en: "At least one device is required",
        cn: "至少需要一台设备",
    },
    {
        key: "groupErrorMsg",
        en: "At least one group is required",
        cn: "至少需要一个组",
    },
    {key: "nameErrorMsg", en: "Name is required", cn: "名称为必填"},
    {
        key: "rawDataErrorMsg",
        en: "Raw data is only available for 5 or less selected devices",
        cn: "原始数据仅可用于5个或更少的选定设备",
    },
    {
        key: "Report_saved_successfully",
        en: "Report has been successfully saved",
        cn: "报告已成功保存",
    },
    {
        key: "Report_deleted_successfully",
        en: "Report has been successfully deleted",
        cn: "报告已成功删除",
    },
    {key: "Data_analytics", en: "Data analytics:", cn: "资料分析"},
    {key: "Data_groups", en: "Data groups", cn: "资料组"},
    {
        key: "confirmDelete",
        en: "Are you sure you want to delete this group?",
        cn: "您确定要删除此节点",
    },
    {
        key: "confirmAction",
        en: "This action can't be undone",
        cn: "此操作无法撤消",
    },
    {key: "delete", en: "Delete", cn: "删除"},
    {key: "Incoming", en: "Incoming", cn: "传入"},
    {key: "Outgoing", en: "Outgoing", cn: "外向"},
    {
        key: "Data_analytics: Reports / Generate report",
        en: "Data analytics: Reports / Generate report",
        cn: "数据分析：报告/生成报告",
    },
    {key: "Data_report", en: "Data report", cn: "数据报告"},
    {key: "Data_range", en: "Data range", cn: "数据范围"},
    {key: "FifteenMinutes", en: "15 minutes", cn: "15分钟"},
    {key: "Hour", en: "Hour", cn: "小时"},
    {key: "Raw", en: "Raw", cn: "原始"},
    {key: "Year", en: "Year", cn: "年"},
    {key: "Month", en: "Month", cn: "月"},
    {key: "Day", en: "Day", cn: "天"},
    {key: "Report_type", en: "Report type", cn: "报告类型"},
    {
        key: "Include_aggregated_data_at_site_level_for_the_selected_time_window",
        en: "Include aggregated data at site level for the selected time window.",
        cn: "在选定的时间范围内，在站点上添加汇总数据。",
    },
    {key: "Items_compare", en: "Items compare", cn: "项目比较"},
    {key: "Generate_report", en: "Generate report", cn: "产生报告"},
    {
        key: "set_schedule_task",
        en: "Set schedule task",
        cn: "设置计划任务",
    },
    {key: "Monthly", en: "Monthly", cn: "每月"},
    {key: "Semesterly", en: "Semesterly", cn: "每半年"},
    {key: "Yearly", en: "Yearly", cn: "每年"},
    {key: "Time_shedule", en: "Time shedule", cn: "时间表"},
    {key: "Daily", en: "Daily", cn: "每天"},
    {key: "Weekly", en: "Weekly", cn: "每周"},
    {key: "Monthly", en: "Monthly", cn: "每月"},
    {key: "Users", en: "Users", cn: "用户"},
    {key: "Data_range", en: "Data range", cn: "数据范围"},
    {key: "Save_task", en: "Save task", cn: "保存"},
    {key: "Custom", en: "Custom", cn: "自定义"},
    {key: "Group_01", en: "Group 01", cn: "组01"},
    {key: "Items", en: "Groups", cn: "组"},
    {key: "Overview", en: "Overview", cn: "总览"},
    {key: "Events", en: "Events", cn: "事件"},
    {key: "Alert_condition", en: "Alert condition", cn: "警报条件"},
    {key: "Connectivity", en: "Connectivity", cn: "连接性"},
    {key: "Information", en: "Information", cn: "信息"},
    {key: "Connected", en: "Connected", cn: "已连接"},
    {key: "Disconnected", en: "Disconnected", cn: "断开"},
    {key: "Documentation", en: "Documentation", cn: "文档"},
    {key: "enableAsset", en: "Enable asset", cn: "启用资产"},
    {key: "disableAsset", en: "Disable asset", cn: "停用资产"},
    {key: "2D_3D_view", en: "2D/3D view", cn: "2D/3D 视图"},
    {key: "Start_navigation", en: "Start navigation", cn: "开始导航"},
    {key: "Explore", en: "Explore:", cn: "探索"},
    {key: "Update_labels", en: " Update labels", cn: "更新标签"},
    {key: "Upload_image", en: "Upload image", cn: "上传图片"},
    {key: "Create", en: "Create", cn: "创建"},
    {key: "Private", en: "Private", cn: "私人的"},
    {key: "Notes", en: "Notes", cn: "笔记"},
    {key: "View_settings", en: "View settings", cn: "查看设置"},
    {key: "Labels", en: "Labels", cn: "标签"},
    {key: "Image", en: "Image", cn: "图片"},
    {key: "Select_device", en: "Select asset...", cn: "选择资产..."},
    {key: "Clear_markers", en: "Clear markers", cn: "清除标记"},
    {key: "Select_image", en: "Select image", cn: "选择图片"},
    {key: "Drop_file_here", en: "Drop file here", cn: "将文件拖到这里"},
    {key: "Update_markers", en: "Update markers", cn: "更新标记"},
    {key: "Markers", en: "Markers", cn: "标记"},
    {key: "Information", en: "Information", cn: "信息"},
    {key: "No_image", en: "No image", cn: "没有图像"},
    {
        key: "Total_active_power",
        en: "Total active power",
        cn: "总有功功率",
    },
    {key: "Notes", en: "Notes", cn: "笔记"},
    {key: "Main_Grid", en: "Main Grid", cn: "主电网"},
    {key: "Generator", en: "Generator", cn: "发电机"},
    {key: "kWh", en: "kWh", cn: "kWh"},
    {key: "Waning", en: "Warning", cn: "警告"},
    {
        key: "Explore:Connectivity",
        en: "Explore: Connectivity",
        cn: "探索：连接性",
    },
    {key: "Hierarchical_view", en: "Hierarchical view", cn: "分层视图"},
    {key: "New", en: "New", cn: "新建"},
    {key: "Explore", en: "Explore:", cn: "探索"},
    {
        key: "Explore_Hierarchical_view",
        en: "Explore:Hierarchical view",
        cn: "探索：分层视图",
    },
    {key: "Site", en: "Site", cn: "站点"},
    {key: "warning", en: "warning", cn: "警告"},
    {key: "Overview", en: "Overview", cn: "总览"},
    {key: "Watchers", en: "Watchers", cn: "观察者"},
    {key: "Events", en: "Events", cn: "事件"},
    {key: "Maintenance", en: "Maintenance", cn: "维护"},
    {
        key: "cancel_presentation",
        en: "Cancel presentation",
        cn: "取消简报",
    },
    {key: "Settings", en: "Settings", cn: "设置"},
    {key: "Good", en: "Good", cn: "好"},
    {key: "Medium", en: "Medium", cn: "中"},
    {key: "Moderate", en: "Moderate", cn: "中等"},
    {key: "Critical", en: "Critical", cn: "严重"},
    {key: "apps", en: "apps", cn: "应用"},
    {
        key: "New_alert_condition",
        en: "New alert condition",
        cn: "新建警报条件",
    },
    {key: "Events", en: "Events", cn: "事件"},
    {key: "Alert_condition", en: "Alert condition", cn: "警报条件"},
    {key: "Asset", en: "Asset", cn: "资产"},
    {key: "None", en: "None", cn: "没有"},
    {key: "On_activation", en: "On activation", cn: "激活时"},
    {key: "On_deactivation", en: "On deactivation", cn: "禁用时"},
    {key: "Active_Intervals", en: "Active intervals", cn: "有效间隔"},
    {key: "Subscribed_Users", en: "Subscribed users", cn: "订阅的用户"},
    {key: "Add_user", en: "Add user", cn: "添加用户"},
    {key: "Save_Alerts", en: "Save alerts", cn: "保存警报"},
    {key: "Cancel", en: "Cancel", cn: "取消"},
    {key: "More_Than", en: "More than", cn: "大于"},
    {key: "Less_Than", en: "Less than", cn: "小于"},
    {
        key: "Alert_does_not_exist",
        en: "Alert does not exist",
        cn: "警报不存在",
    },
    {key: "Data_analytics", en: "Data analytics: ", cn: "资料分析"},
    {
        key: "Reports_Scheduled_task",
        en: " Reports / Scheduled task",
        cn: "报告/计划任务",
    },
    {key: "Activities_log", en: "Activities log", cn: "活动日志"},
    {key: "Users_and_groups", en: "Users and groups", cn: "用户和组"},
    {
        key: "Error_msg_name",
        en: "This feature is for EDCS only",
        cn: "此功能仅适用于EDCS",
    },
    {key: "presetName", en: "PRESET", cn: "预设"},
    {key: "humidity", en: "HUMIDITY", cn: "湿度"},
    {key: "salt", en: "SHORE LINE DISTANCE", cn: "岸线距离"},
    {
        key: "averageYearlyTemperature",
        en: "AVERAGE YEARLY T",
        cn: "年平均温度",
    },
    {key: "voltage", en: "VOLTAGE", cn: "电压"},
    {key: "vibration", en: "VIBRATION", cn: "振动"},
    {key: "sO2Corrosion", en: "CORROSION", cn: "腐蚀"},
    {key: "dust", en: "DUST LEVEL", cn: "粉尘级别"},
    {key: "documentName", en: "DOCUMENT", cn: "文件"},
    {key: "weight", en: "WEIGHT", cn: "大小"},
    {key: "type", en: "TYPE", cn: "类型"},
    {key: "notificationTypes", en: "TYPE", cn: "类型"},
    {key: "alertConditionParticularDevice", en: "TYPE", cn: "类型"},
    {key: "alertConditionAllAlerts", en: "TYPE", cn: "类型"},
    {key: "documentationColumn", en: "TYPE", cn: "类型"},
    {key: "eventList", en: "TYPE", cn: "类型"},
    {key: "assetPageDocumentationColumn", en: "TYPE", cn: "类型"},
    {key: "createDate", en: "UPLOADED DATE", cn: "上传日期"},
    {key: "category", en: "Category", cn: "类别"},
    {key: "cateory", en: "CATEGORY", cn: "类别"},
    {key: "author", en: "AUTHOR", cn: "作者"},
    {key: "culture", en: "CULTURE", cn: "文化"},
    {key: "documentationColumnCulture", en: "CULTURE", cn: "文化"},
    {key: "documentationColumnWeight", en: "WEIGHT", cn: "大小"},
    {key: "documentationColumnType", en: "TYPE", cn: "类型"},
    {
        key: "documentationColumnCreatedDate",
        en: "UPLOADED DATE",
        cn: "上传日期",
    },
    {
        key: "documentationColumnCreatedCategory",
        en: "CATEGORY",
        cn: "类别",
    },
    {key: "documentationColumnCreatedAuthor", en: "AUTHOR", cn: "作者"},
    {key: "dueDate", en: "DUE DATE", cn: "截止日期"},
    {key: "priority", en: "PRIORITY", cn: "优先"},
    {key: "description", en: "DESCRIPTION", cn: "描述"},
    {key: "activitiesLogColumnsItemDesc", en: "DESCRIPTION", cn: "描述"},
    {key: "userData", en: "USER", cn: "用户"},
    {key: "status", en: "STATUS", cn: "状态"},
    {key: "executionDate", en: "EXECUTION DATE", cn: "执行日期"},
    {key: "notes", en: "NOTES", cn: "笔记"},
    {key: "user", en: "USER", cn: "用户"},
    {key: "assignedUser", en: "USER", cn: "用户"},
    {key: "role", en: "ROLE", cn: "角色"},
    {key: "assignedUserRole", en: "ROLE", cn: "角色"},
    {key: "job", en: "JOB", cn: "工作"},
    {key: "assignedUserJob", en: "JOB", cn: "工作"},
    {key: "itemContext", en: "ASSETS", cn: "资产"},
    {key: "assetItemDataGroupListItemContext", en: "GROUPS", cn: "组"},
    {key: "assetItemDataGroupListCompany", en: "MEASURES", cn: "措施"},
    {key: "notificationTypesChannels", en: "CHANNELS", cn: "频道"},
    {key: "company", en: "CLASS", cn: "类"},
];

export default temp;
